version: '3'

services:
# Commit
  unit:
    image: openjdk:8u162-jdk
    volumes:
      - .:/appsrc
      - ./rootGradle:/root/.gradle
    working_dir: /appsrc
    command: bash -c "./gradlew clean build copyDockerFiles"

  app:
    build:
      context: ./backend-config-service/build/dockerfile/
    image: thesis-configservice:snapshot

# Staging
  eurekapeer1:
    image: thesis-eurekaservice:snapshot  # TODO fixed?
#    image: localhost:5000/thesis-eurekaservice:latest  # TODO fixed?
    environment:
      - PROFILE=peer1
    ports:
      - "7761:8761"

  eurekapeer2:
    image: thesis-eurekaservice:snapshot  # TODO fixed?
#    image: localhost:5000/thesis-eurekaservice:latest  # TODO fixed?
    environment:
      - PROFILE=peer2
    ports:
      - "7762:8761"

  configservice:
    image: thesis-configservice:snapshot
    depends_on:
      - eurekapeer1
      - eurekapeer2
    environment:
       EUREKASERVICE_URI: "http://eurekapeer1:8761/eureka/,http://eurekapeer2:8761/eureka/"
       EUREKASERVICE_PORT: "8761"
       ENCRYPT_KEY: "COMMON_SYMMETRIC_KEY"
    ports:
      - "7888:8888"

  staging:
    image: openjdk:8u162-jdk
    depends_on:
      - eurekapeer1
      - eurekapeer2
      - configservice
    volumes:
      - .:/appsrc
      - ./rootGradle:/root/.gradle
    environment:
      - EUREKASERVICE_URI_1=http://eurekapeer1:8761
      - EUREKASERVICE_URI_2=http://eurekapeer2:8761
      - EUREKASERVICE_PORT=8761
      - CONFIGSERVICE_URI=http://configservice:8888
      - ENCRYPT_KEY="COMMON_SYMMETRIC_KEY"
    working_dir: /appsrc
    command: bash -c "ping -c 1 eurekapeer1 && ping -c 1 eurekapeer2 && ping -c 1 configservice && ./gradlew integTest"
