server.port: 8888

spring:
  cloud:
    config:
      # discovery needed?
      discovery.enabled: true
      server:
        git:
          uri: https://github.com/kdzido/thesis-config/
          searchPaths: sampleservice,todoservice,zuulservice

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/


# logging
logging.level:
  com.netflix: WARN
  org.springframework.web: WARN
  com.kdzido.thesis: DEBUG